style: Adjust indent to 2 spaces

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -16,28 +16,28 @@ install_path="$ASDF_INSTALL_PATH" && logdebug "install_path=$install_path"
 download_path="$ASDF_DOWNLOAD_PATH" && logdebug "download_path=$download_path"
 
 if [ "$install_type" != "version" ]; then
-    logexit "asdf-$tool_name supports release installs only."
+  logexit "asdf-$tool_name supports release installs only."
 fi
 
 (
-    mkdir -p "$install_path"
-    mkdir -p "$install_path/bin"
+  mkdir -p "$install_path"
+  mkdir -p "$install_path/bin"
 
-    cp -r "$download_path"/* "$install_path"
-    logsuccess "Copied downloaded files from '$download_path' to '$install_path'."
+  cp -r "$download_path"/* "$install_path"
+  logsuccess "Copied downloaded files from '$download_path' to '$install_path'."
 
-    mv "$install_path/$tool_name" "$install_path/bin/"
-    logsuccess "Moved $tool_name binary to '$install_path/bin/'."
+  mv "$install_path/$tool_name" "$install_path/bin/"
+  logsuccess "Moved $tool_name binary to '$install_path/bin/'."
 
-    test -x "$install_path/bin/$tool_name" \
-        || logexit "'$install_path/bin/$tool_name' not executable."
+  test -x "$install_path/bin/$tool_name" \
+    || logexit "'$install_path/bin/$tool_name' not executable."
 
-    if ! "$install_path/bin/$tool_name" --help > /dev/null; then
-        logexit "Executing '$install_path/bin/$tool_name --help' failed."
-    fi
+  if ! "$install_path/bin/$tool_name" --help > /dev/null; then
+    logexit "Executing '$install_path/bin/$tool_name --help' failed."
+  fi
 
-    logsuccess "$tool_name '$install_version' installed."
+  logsuccess "$tool_name '$install_version' installed."
 ) || (
-    rm -rf "$install_path"
-    logexit "An error ocurred while installing $tool_name to '$install_path'."
+  rm -rf "$install_path"
+  logexit "An error ocurred while installing $tool_name to '$install_path'."
 )
